import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../lib/api.js";
import { Card, Gauge } from "../components/ui.jsx";
import { IconClinic, IconStethoscope, IconWarn } from "../components/icons.jsx";

export default function Diagnose() {
  const [tasks, setTasks] = useState([]);
  const [models, setModels] = useState([]);
  const [taskKey, setTaskKey] = useState("diabetes");
  const [values, setValues] = useState({});
  const [result, setResult] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  useEffect(() => {
    api.tasks().then((t) => {
      setTasks(t);
      const first = t.find((x) => x.key === "diabetes") ?? t[0];
      applyTask(first);
    });
    api.models().then(setModels).catch(() => {});
  }, []);

  const applyTask = (spec) => {
    setTaskKey(spec.key);
    const mid = {};
    spec.features.forEach((f) => {
      mid[f.name] = f.lo + (f.hi - f.lo) * (f.direction > 0 ? 0.38 : 0.62);
    });
    setValues(mid);
    setResult(null);
    setError(null);
  };

  const task = tasks.find((t) => t.key === taskKey);
  const hasModel = models.some((m) => m.task === taskKey);

  const fill = (frac) => {
    if (!task) return;
    const v = {};
    task.features.forEach((f) => {
      v[f.name] = f.lo + (f.hi - f.lo) * frac;
    });
    setValues(v);
  };

  const run = async () => {
    setBusy(true);
    setError(null);
    try {
      const r = await api.inference(taskKey, values);
      setResult(r);
    } catch (e) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  };

  const riskColor = useMemo(() => {
    if (!result) return "var(--cyan)";
    return result.risk >= 0.5 ? "var(--red)" : "var(--green)";
  }, [result]);

  if (!task) return <div className="page container" />;

  return (
    <div className="page">
      <div className="container">
        <div className="page-head">
          <div className="eyebrow">clinic console</div>
          <h1 className="h2" style={{ maxWidth: "34ch" }}>
            Point-of-care screening with the federated global model.
          </h1>
          <p className="lead">
            This is the app that runs on a clinic tablet: enter today's observations, get the shared model's
            risk read and the factors behind it. The model arrived over the federation — the patient record
            stays here.
          </p>
        </div>

        <div className="banner" style={{ marginBottom: 26 }}>
          <IconWarn width={17} />
          <span>
            <b>Research demonstration.</b> Risk outputs are generated by a small quantum classifier trained on
            synthetic data for this prototype. Do not use for clinical decision-making.
          </span>
        </div>

        <div className="grid" style={{ gridTemplateColumns: "1.15fr 0.85fr", alignItems: "start" }}>
          {/* ------------------------------------------------------- inputs */}
          <Card
            title={task.display_name}
            sub={task.subtitle}
            icon={<IconStethoscope width={17} />}
            right={
              <div className="seg">
                {tasks.map((t) => (
                  <button key={t.key} className={t.key === taskKey ? "active" : ""} onClick={() => applyTask(t)}>
                    {t.name.split(" ")[0]}
                  </button>
                ))}
              </div>
            }
          >
            <div className="stack" style={{ gap: 20 }}>
              <div className="row" style={{ gap: 8 }}>
                <span className="notice" style={{ marginRight: 4 }}>presets:</span>
                <button className="btn btn-ghost btn-sm" onClick={() => fill(0.35)}>low suspicion</button>
                <button className="btn btn-ghost btn-sm" onClick={() => fill(0.62)}>moderate</button>
                <button className="btn btn-ghost btn-sm" onClick={() => fill(0.85)}>high suspicion</button>
              </div>

              {task.features.map((f) => (
                <div className="field" key={f.name}>
                  <label>
                    {f.label} <span className="mono">{fmt(values[f.name])} {f.unit}</span>
                  </label>
                  <input
                    type="range"
                    min={f.lo}
                    max={f.hi}
                    step={(f.hi - f.lo) / 200}
                    value={values[f.name] ?? f.lo}
                    style={{ "--fill": `${(((values[f.name] ?? f.lo) - f.lo) / (f.hi - f.lo)) * 100}%` }}
                    onChange={(e) => setValues((v) => ({ ...v, [f.name]: +e.target.value }))}
                  />
                </div>
              ))}

              <div className="spread" style={{ marginTop: 6 }}>
                <span className="notice">
                  {hasModel
                    ? "global model: latest federated bundle for this task"
                    : "no trained bundle for this task yet — launch a run in the console"}
                </span>
                <button className="btn btn-primary" onClick={run} disabled={busy || !hasModel}>
                  {busy ? "running inference…" : "Run screening"}
                </button>
              </div>
              {error && (
                <div className="banner">
                  <IconWarn width={16} />
                  <span>
                    {error} {!hasModel && (
                      <Link to="/dashboard" style={{ textDecoration: "underline" }}>
                        Open the console
                      </Link>
                    )}
                  </span>
                </div>
              )}
            </div>
          </Card>

          {/* ------------------------------------------------------ results */}
          <div className="stack">
            <Card title="Risk assessment" icon={<IconClinic width={17} />} sub={result ? `model ${result.model.name}` : "awaiting input"}>
              <div className="gauge-wrap">
                <Gauge value={result?.risk ?? 0} color={riskColor} />
                <div className="gauge-label" style={{ color: riskColor }}>
                  {result ? result.label : "—"}
                </div>
                <div className="notice">
                  {result
                    ? `P(positive) = ${result.risk.toFixed(3)} · threshold 0.5 · bundle val-acc ${(result.model.val_acc ?? 0).toFixed(3)}`
                    : "adjust the panel and run screening"}
                </div>
              </div>
            </Card>

            <Card title="Contributing factors" sub="change in risk if this measurement were at cohort median">
              {result ? (
                <div className="stack" style={{ gap: 12 }}>
                  {result.contributions.slice(0, 6).map((c) => {
                    const pct = Math.min(Math.abs(c.impact) / 0.25, 1) * 100;
                    const up = c.impact > 0;
                    return (
                      <div key={c.name} className="bar-row">
                        <span className="muted" style={{ fontSize: 12.5 }}>{c.label}</span>
                        <div className="bar-track">
                          <div
                            className="bar-fill"
                            style={{
                              width: `${pct}%`,
                              background: up
                                ? "linear-gradient(90deg,#f87171aa,#f87171)"
                                : "linear-gradient(90deg,#22d3eeaa,#22d3ee)",
                            }}
                          />
                        </div>
                        <span className="mono" style={{ color: up ? "var(--red)" : "var(--cyan)", textAlign: "right" }}>
                          {c.impact > 0 ? "+" : ""}
                          {(c.impact * 100).toFixed(1)}
                        </span>
                      </div>
                    );
                  })}
                  <p className="notice" style={{ marginTop: 4 }}>
                    Signed deltas in percentage points; positive pushes risk up. Computed by one-at-a-time
                    perturbation against the coordinator's reference medians.
                  </p>
                </div>
              ) : (
                <p className="muted" style={{ fontSize: 13.5 }}>
                  After screening, the model explains itself: each factor's marginal effect on the risk score.
                </p>
              )}
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}

const fmt = (v) => (v == null ? "—" : Math.abs(v) >= 100 ? v.toFixed(0) : v.toFixed(1));
